layout_spectrum: 0.26382327291616564
typography_spectrum: 0.1649901225023193
color:
  brandStrength: 0.4798547385244787
  lightness: 0.4509229620342318
  saturation: 0.6931871866886642
  rhythmicContrast: 0.14921946855741416
  brandColors:
    - '#F4F2EE'
    - '#FAF8F2'
    - '#FDFCF9'
    - '#EFECE9'
    - '#FFFFFF'
coverPrefs:
  filter: false
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
name: blog
content: []
url: 'https://thegrid.ai/blog'
title: the blog
description: available 24/7.. or whilst thoughts last..
analytics:
  google: UA-100545624-1
github: true
