layout_spectrum: 0.1618839226173477
typography_spectrum: 0.16608750781975687
color:
  brandStrength: 0.5964079449004909
  lightness: 0.6927032268238207
  saturation: 0.12699369202478614
  rhythmicContrast: 0.4262965645228909
  brandColors:
    - '#F4F2EE'
    - '#FAF8F2'
    - '#FDFCF9'
    - '#EFECE9'
    - '#FFFFFF'
coverPrefs:
  filter: false
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
name: the blog
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/5715335e-8acd-4773-89e8-51454948619e.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/5715335e-8acd-4773-89e8-51454948619e.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
url: 'https://thegrid.ai/blog'
title: the blog
description: available 24/7.. or whilst thoughts last..
analytics:
  google: UA-100545624-1
github: true
purpose: []
author:
  name: adec
  email: adrian@bbiab.com
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/e260b62f-bbfd-420e-9a7b-268c413cefd2.ico
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/081567e8-66d9-40d7-8209-394e80836c8a.png
