layout_spectrum: 0.20086041241146552
typography_spectrum: 0.16953600332048713
color:
  brandStrength: 0.5985168022842211
  lightness: 0.6968808142049698
  saturation: 0.12281819506400808
  rhythmicContrast: 0.4275110808213121
  brandColors:
    - '#F4F2EE'
    - '#FAF8F2'
    - '#FDFCF9'
    - '#EFECE9'
    - '#FFFFFF'
coverPrefs:
  filter: false
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
name: the blog
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/76ad835d-0b57-413e-befa-d64d8d9298dd.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/76ad835d-0b57-413e-befa-d64d8d9298dd.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/09fce385-ea46-4c80-b404-a8e275d13241.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/09fce385-ea46-4c80-b404-a8e275d13241.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
url: 'https://thegrid.ai/blog'
title: the blog
description: available 24/7.. or whilst thoughts last..
analytics:
  google: UA-100545624-1
github: true
purpose: []
author:
  name: adec
  email: adrian@bbiab.com
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/e260b62f-bbfd-420e-9a7b-268c413cefd2.ico
